### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by dcordero**
Just adding syntax sugar to selectors and removing some redundant imports.

Congrats for the project guys, it is a really helpful repo as a clean reference to explain and to understand some concepts.

### CODE REVIEW

**Comment by pedrovgs** [comment]
👍

**Comment by Serchinastico** [comment]
:+1:

**Comment by davideme** [comment]
👍

**Comment by Serchinastico** [comment]
We are trying to fix the travis build, we'll merge this PR as soon as that happens :)

**Comment by dcordero** [comment]
Great, thanks, no hurries at all :D 

It looks like some deprecated option in the Cocoapods 1.0.0 BTW https://github.com/CocoaPods/CocoaPods/issues/4706

**Comment by pedrovgs** [comment]
@Serchinastico maybe is going to be easier if @dcordero updates the Podfile to match with the cocoapods 1.0.0 specs :)

**Comment by davideme** [comment]
I'm on it.

**Comment by pedrovgs** [comment]
Coooool thanks :)

**Comment by Serchinastico** [comment]
@dcordero can you update your branch with master to see if the build passes?

**Comment by dcordero** [comment]
Done ✅ 

Thanks guys

**Comment by pedrovgs** [comment]
Thanks @dcordero

**Pull request merged**
