### PR TITLE
Add unit tests to BothamStoryboard

### PR DESCRIPTION
**Pull request by dcordero**
Add Unit Tests to BothamStoryboard

### CODE REVIEW

**Comment by davideme** [comment]
👍

**Comment by pedrovgs** [comment]
Hi @dcordero thanks for your contribution. I've seen that we are checking that the instance obtained is not nil, but can't we ask the view controller obtained something we could use to know that the one obtained is the correct one?

**Comment by dcordero** [comment]
Hi @pedrovgs that is a good point. 
I have just made a commit changing the asserts to make them more clear.

But to be honest I am not sure about those assertions, because both of them (to not be nil or to be an instance of DummyViewController) are already guaranteed by the language since we are already receiving a non optional `DummyViewController` as result of BothamStoryboard.

In case of failure in the expected behaviour, these tests will actually crash before reaching the asserts because of the implicit casting. `as! T`

**Comment by pedrovgs** [comment]
Hi @dcordero sorry for the delay, I've been out for some time. Could you update this PR with master? Once be updated we can merge it :) Thank you so much!

**Comment by dcordero** [comment]
@pedrovgs Done ✅ 🍷

**Comment by davideme** [comment]
A tu salud!

**Pull request merged**
