### PR TITLE
Set Presenter as Generic

### PR DESCRIPTION
**Pull request by davideme**
We loose name completion on the storyboards but we gain generic presenter and avoid down casting or runtime calls.

### CODE REVIEW

**Comment by pedrovgs** [comment]
:+1:

**Comment by Serchinastico** [comment]
Fix tests & :+1:

**Comment by davideme** [comment]
Please check again this PR, with the additionals init in order to get it working.

**Comment by davideme** [comment]
I have to investigate a little bit more, but I think IBOutlet are not working anymore with Generic ViewController, so we have to discard this solution.

**Comment by pedrovgs** [comment]
Can we close this PR then?

**Pull request closed without merging**
